### ISSUE TITLE
Scroll bars in empty interactive holder

### ISSUE THREAD

**Issue by frcroth** [hpi-swa-lab/qinoq#1010]
**To Reproduce**
1. Open an empty editor
2. Create an interactive
3. Drag it out

**Expected behavior**
No scrollbars

**Screenshots**
![image](https://user-images.githubusercontent.com/6863832/122197326-5c128300-ce98-11eb-84e1-e0416eae91f8.png)

**Comment by linusha** [comment]
Fixed in 521970d50aad028935ab34fba08135ac858d25f2
