### ISSUE TITLE
Zooming in interactive with text has weird behavior

### ISSUE THREAD

**Issue by T4rikA** [hpi-swa-lab/qinoq#1013]
**Describe the bug**
When zooming the interactive in the editor the scaling of the text is off

**To Reproduce**
1. Open interactive in editor
2. Add text label
3. zoom the interactive
4. text label will become larger/ smaller over the time with same zoom

**Expected behavior**
at same zoom same text size

**Comment by linusha** [comment]
Should be fixed with 7a5a0458fa65da3b4665e249e7077f76881340ae. Since we do not recalculate the extent anymore when zooming in the interactive, the size calculation for the font size is not triggered.
