### ISSUE TITLE
Copy of sequences destroys graph

### ISSUE THREAD

**Issue by T4rikA** [hpi-swa-lab/qinoq#1021]
**Describe the bug**
When copying  a sequence in the graph there will be keyframes of the copied sequence in the old sequence
**To Reproduce**
1. copy a sequence
2. look at the keyframes in the old sequence

**Expected behavior**
Nothing changes in old sequence

**Comment by linusha** [comment]
Fixed in 377614283ab2665ef8371876a9b440b5effd3d2b
