### ISSUE TITLE
Graph doesn't update when adding morphs to sequence

### ISSUE THREAD

**Issue by T4rikA** [hpi-swa-lab/qinoq#1022]
**Describe the bug**
Sometimes the graph doesn't update when adding new morphs to a sequence
You can't expand the graph because there are no items listed, this fixes after time/ with new events

**To Reproduce**
not clear

**Expected behavior**
everything is consistent

**Comment by linusha** [comment]
The description here is quite vague, a lot of cases should be fixed now with a41d313611732b458f121f73a8a715a9c90e6320. Will be reopened if occurring again.
