### ISSUE TITLE
Indicator when trying to draw in overview timeline

### ISSUE THREAD

**Issue by T4rikA** [hpi-swa-lab/qinoq#1028]
There should be an indicator/ warning that you cant create morphs via drag and drop in the overview timeline

**Comment by frcroth** [comment]
@linusha if you aren't working with PRs anymore, perhaps add the commit id here to make the closing of issues more nachvollziehbar

**Comment by linusha** [comment]
> @linusha if you aren't working with PRs anymore, perhaps add the commit id here to make the closing of issues more nachvollziehbar

Absolutely. There was some confusion about this ticket, sorry for that.
It is now actually fixed with 84055c24a3a7a41d2d1324286f2330b5ef906c07.
