### ISSUE TITLE
Lottie morphs have the same animation after bundling

### ISSUE THREAD

**Issue by T4rikA** [hpi-swa-lab/qinoq#1036]
**Describe the bug**
When you copy a morph  with our tool they have the same animation after bundling
Read comment!

**To Reproduce**
1. Create interactive with lottie morph in one sequence
2. copy morph multiple times and change lottie animation (and keyframes if you want)
3. in the world everything works fine
4. when bundling the scrollytelling they all have the same animation

**Expected behavior**
Different animations for each morph

**Comment by linusha** [comment]
I could not reproduce this on the newest lively.next master, but will try some more.

**Comment by linusha** [comment]
![Peek 2021-09-13 23-06](https://user-images.githubusercontent.com/14252419/133156518-d7d93c01-ff60-4688-9b94-d1ca170e1cc0.gif)

I tried some more, but could not reproduce it. Here are four LottieMorphs where three are copies of the lower left one.
The current goal is to make qinoq ready for a first production run, with heavier use this might reappear.
