### ISSUE TITLE
Connections to OnScrollChange of the interactive are not removed

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa-lab/qinoq#1047]
**Describe the bug**
When removing something like a LottieMorph that has a OnScrollChange connected those connections on removal of the object are not correctly removed

**Comment by linusha** [comment]
To reproduce:
1. Create a new interactive
2. Add a morph to it
3. Connect onScrollChange of the Interactive with the newly added morph
4. Delete the morph (e.g., by using the Trashcan-Halo)
5. See the connection persisting in the attributeConnections of the interactive

**Comment by linusha** [comment]
This is rudimentary fixed in 30d18f653837cfa082838c73245064c9cc889214.
